create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_egresso bigint not null, id_curso bigint not null, primary key (id_egresso, id_curso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FK6951t4fq33wtoi0qj6hsouhtw foreign key (id_curso) references contato (id_depoimento);
alter table curso_egresso add constraint FKjxl2peve48gul6mrpr726nv6i foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_egresso bigint not null, id_curso bigint not null, primary key (id_egresso, id_curso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FK6951t4fq33wtoi0qj6hsouhtw foreign key (id_curso) references contato (id_depoimento);
alter table curso_egresso add constraint FKjxl2peve48gul6mrpr726nv6i foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_egresso bigint not null, id_curso bigint not null, primary key (id_egresso, id_curso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FK6951t4fq33wtoi0qj6hsouhtw foreign key (id_curso) references contato (id_depoimento);
alter table curso_egresso add constraint FKjxl2peve48gul6mrpr726nv6i foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_egresso bigint not null, id_curso bigint not null, primary key (id_egresso, id_curso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FK6951t4fq33wtoi0qj6hsouhtw foreign key (id_curso) references contato (id_depoimento);
alter table curso_egresso add constraint FKjxl2peve48gul6mrpr726nv6i foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_curso bigint not null, id_egresso bigint not null, primary key (id_curso, id_egresso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FKamo5snuu8crojc6nqfrxawryx foreign key (id_egresso) references contato (id_depoimento);
alter table curso_egresso add constraint FKbmckw20la8cgjg3oo3og1p0um foreign key (id_curso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_curso bigint not null, id_egresso bigint not null, primary key (id_curso, id_egresso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FKamo5snuu8crojc6nqfrxawryx foreign key (id_egresso) references contato (id_depoimento);
alter table curso_egresso add constraint FKbmckw20la8cgjg3oo3og1p0um foreign key (id_curso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_curso bigint not null, id_egresso bigint not null, primary key (id_curso, id_egresso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FKamo5snuu8crojc6nqfrxawryx foreign key (id_egresso) references contato (id_depoimento);
alter table curso_egresso add constraint FKbmckw20la8cgjg3oo3og1p0um foreign key (id_curso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_curso bigint not null, id_egresso bigint not null, primary key (id_curso, id_egresso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FKamo5snuu8crojc6nqfrxawryx foreign key (id_egresso) references contato (id_depoimento);
alter table curso_egresso add constraint FKbmckw20la8cgjg3oo3og1p0um foreign key (id_curso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_curso bigint not null, id_egresso bigint not null, primary key (id_curso, id_egresso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FKamo5snuu8crojc6nqfrxawryx foreign key (id_egresso) references contato (id_depoimento);
alter table curso_egresso add constraint FKbmckw20la8cgjg3oo3og1p0um foreign key (id_curso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_curso bigint not null, id_egresso bigint not null, primary key (id_curso, id_egresso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FKamo5snuu8crojc6nqfrxawryx foreign key (id_egresso) references contato (id_depoimento);
alter table curso_egresso add constraint FKbmckw20la8cgjg3oo3og1p0um foreign key (id_curso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
create table cargo (id_cargo bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id_cargo)) engine=InnoDB;
create table contato (id_contato bigint not null, nome varchar(255), url_logo varchar(255), id_curso bigint not null, nivel varchar(255), id_depoimento bigint not null auto_increment, data datetime(6), texto varchar(255), id_egresso bigint, primary key (id_depoimento)) engine=InnoDB;
create table contato_egresso (id_contato bigint not null, id_egresso bigint not null, primary key (id_contato, id_egresso)) engine=InnoDB;
create table curso_egresso (id_curso bigint not null, id_egresso bigint not null, primary key (id_curso, id_egresso)) engine=InnoDB;
create table egresso (id_egresso bigint not null auto_increment, cpf varchar(255), email varchar(255), nome varchar(255), resumo varchar(255), url_foto varchar(255), primary key (id_egresso)) engine=InnoDB;
create table faixa_salario (id_faixa_salario bigint not null auto_increment, descricao varchar(255), primary key (id_faixa_salario)) engine=InnoDB;
create table prof_egresso (id_prof_egresso bigint not null auto_increment, data_registro datetime(6), descricao varchar(255), empresa varchar(255), id_cargo bigint, id_egresso bigint, id_faixa_salario bigint, primary key (id_prof_egresso)) engine=InnoDB;
alter table contato add constraint FKmod2gngjq40m2xotjb3ctdij0 foreign key (id_egresso) references egresso (id_egresso);
alter table contato_egresso add constraint FKtdg2qklhyrc8xlogc3cxq15ab foreign key (id_egresso) references contato (id_depoimento);
alter table contato_egresso add constraint FKlsqe9tu10mpsghxyvoiddwawu foreign key (id_contato) references egresso (id_egresso);
alter table curso_egresso add constraint FKamo5snuu8crojc6nqfrxawryx foreign key (id_egresso) references contato (id_depoimento);
alter table curso_egresso add constraint FKbmckw20la8cgjg3oo3og1p0um foreign key (id_curso) references egresso (id_egresso);
alter table prof_egresso add constraint FKh5jkeyy3ub129cwwxgil0s24k foreign key (id_cargo) references cargo (id_cargo);
alter table prof_egresso add constraint FKsmn5g2x7tbhxd4mclkig6ft2c foreign key (id_egresso) references egresso (id_egresso);
alter table prof_egresso add constraint FKtqbm76xvp3sohipppboj7dk6u foreign key (id_faixa_salario) references faixa_salario (id_faixa_salario);
